### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [CornellB02/Steak-Book#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments

1. Hey Cornell, I'd make sure to specify that we're Hosting on Render as your 1st Feature. Additionally, I would mark that it should only take 0.5 days to implement your Hosting as we have a Render Push Party.
2. For your User Auth MVP, that should unofficially include your Splash Page as that will offer your users a chance to Sign Up or Login. I would also make a note that on unsuccessful sign up or login, errors will be rendered.
3. Additionally, Profile management will not factor into your User Auth Feature. Instead, you could offer Profiles as a Bonus Feature down the line. User Auth should only focus on Sign Up, Sign In, Logout functionality.
4. Your four Main Features' bullets are a bit sparse as of now and I'd like to see more thought on these. I can provide an example. Currently, your Court Reviews feature lists that you'll allow User to leave persisted reviews and delete them. What I'd expect to see is more along the lines of:
+ While logged out, Users will be able to observe Reviews left by other Users.
+ Signed In Users will be able to leave Reviews on a Court's Show Page.
+ Signed In Users will be able to delete Reviews if they are the author of that Review.
Hope this gives a better idea.
5. Tagging onto your current Features, I'm happy with Feature 1: Courts, Feature 2: Ratings/Reviews - CRUD, Feature 3: Search, Feature 4: Reservations -  CRUD. ***Messaging/Notifications*** feels more like a Bonus, which should be listed below your first 7 Features.
6. Also, your estimated time is putting your work at 10 days (with Render Hosting and Production README). We have roughly 14 official days to work on this project, so I would reallocate a lot of time for Courts and Reviews as the former will need a lot of structure/seeding and the latter is your main CRUD feature.

Please let me know once you've implemented these corrections/additions.

**Comment by keginzburg** [comment]
Hey Cornell, this is all looking good, but I need some clarification. Is your `Suggestion Dashboard` Feature your main `Courts` feature? OpenTable tends to offer some type of Index page with different kinds of Restaurant Listings. I imagine this will need the same for Court Listings. Please let me know below in a comment.

**Comment by CornellB02** [comment]
Yea on the home page for open table right below the area you use search there's a area that looks sort of like suggested restaurants based on different topics. I thought I would try to implement that but I did forget to mention the a index page for the court. Im going to switch those.

**Comment by keginzburg** [comment]
Sounds good. Once that is clarified, then this document should be solid. Awesome work!
